name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir public

          find . -name "*.md" -not -path "./public/*" -not -path "./.github/*" | while read -r file; do
            rel_path="${file#./}"
            out_path="public/${rel_path%.md}.html"
            mkdir -p "$(dirname "$out_path")"
            pandoc "$file" -s -o "$out_path" --metadata title="$(basename "${file%.md}")"
          done
          mv ./public/README.html ./public/index.html

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
